apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: maia
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>MAIA Frontend on EKS</title>
      </head>
      <body>
        <h1>MAIA Frontend (EKS)</h1>
        <p>Frontend temporal para pruebas iniciales.</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 847964925141.dkr.ecr.us-east-1.amazonaws.com/maia-dev-ecr:frontend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: maia
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
